version: "3"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "5006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: db_komunikasi_data
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  app:
    build: 
      context: ./app
    restart: always
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 5008:8080
    depends_on:
      - app
      - db
